"""Patch generation schemas, diff validation, and safety verification.

Enforces policy rules: forbidding test file modifications, bounding diff size,
rejecting suspicious system calls, and verifying git apply compatibility.
"""

from dataclasses import dataclass
from pathlib import Path
import re
import subprocess
from typing import Any, Literal

from pydantic import BaseModel
from unidiff import PatchSet

from reposage.config import settings
from reposage.ingest.walker import is_forbidden_file, is_test_file

SUSPICIOUS_CALL_PATTERNS = re.compile(
    r"\b(os\.system|subprocess\.|socket\.|eval\(|exec\(|shutil\.rmtree\(|urllib\.request|requests\.)"
)


class PatchProposal(BaseModel):
    """Structured proposal generated by the patch node model."""

    root_cause: str
    files: list[str]
    unified_diff: str
    rationale: str
    confidence: Literal["low", "medium", "high"] = "medium"


@dataclass
class ValidationResult:
    """Outcome of patch policy assertions."""

    ok: bool
    errors: list[str]


class PatchValidator:
    """Verifies that candidate diffs comply with safety invariants."""

    def validate(self, diff_text: str, snapshot_root: Path) -> ValidationResult:
        """Execute deterministic policy checks against unified diff."""
        errors: list[str] = []

        if not diff_text or not diff_text.strip():
            return ValidationResult(ok=False, errors=["empty_diff"])

        # 1. Check for newly introduced dangerous system calls
        for line in diff_text.splitlines():
            if line.startswith("+") and not line.startswith("+++"):
                if SUSPICIOUS_CALL_PATTERNS.search(line):
                    errors.append("suspicious_calls")
                    break

        # 2. Check for test tampering from diff file headers
        for line in diff_text.splitlines():
            if line.startswith("--- ") or line.startswith("+++ "):
                f_path = line[4:].strip().lstrip("ab/")
                if is_test_file(f_path) or f_path.endswith(("conftest.py", "pytest.ini", "tox.ini")):
                    if f"touches_test:{f_path}" not in errors:
                        errors.append(f"touches_test:{f_path}")

        # 3. Parse unified diff
        try:
            patch_set = PatchSet(diff_text)
        except Exception as parse_err:
            errors.append(f"malformed_diff: {parse_err}")
            return ValidationResult(ok=False, errors=errors)

        # 2. File count constraint
        if len(patch_set) > settings.patch_max_files:
            errors.append(f"too_many_files ({len(patch_set)} > {settings.patch_max_files})")

        total_changed_lines = 0

        # 3. Inspect individual modified files
        for patched_file in patch_set:
            target_path = patched_file.path

            # Test tampering check
            if is_test_file(target_path) or target_path.endswith(
                ("conftest.py", "pytest.ini", "tox.ini")
            ):
                errors.append(f"touches_test:{target_path}")

            # Forbidden files (e.g. .env, pem)
            if is_forbidden_file(Path(target_path)):
                errors.append(f"forbidden:{target_path}")

            # Binary or rename check
            if patched_file.is_binary_file or patched_file.is_rename:
                errors.append(f"unsupported_change:{target_path}")

            # Containment check
            try:
                resolved = (snapshot_root / target_path).resolve()
                resolved.relative_to(snapshot_root.resolve())
            except ValueError:
                errors.append(f"path_escape:{target_path}")

            total_changed_lines += patched_file.added + patched_file.removed

        # 4. Maximum changed lines constraint
        if total_changed_lines > settings.patch_max_lines_changed:
            errors.append(
                f"too_many_lines ({total_changed_lines} > {settings.patch_max_lines_changed})"
            )

        # 5. Check for newly introduced dangerous system calls
        for line in diff_text.splitlines():
            if line.startswith("+") and not line.startswith("+++"):
                if SUSPICIOUS_CALL_PATTERNS.search(line):
                    errors.append("suspicious_calls")
                    break

        # 6. Check clean applicability via git apply --check if repo exists
        if snapshot_root.exists() and (snapshot_root / ".git").exists():
            try:
                proc = subprocess.run(
                    ["git", "apply", "--check", "-"],
                    input=diff_text,
                    text=True,
                    cwd=snapshot_root,
                    capture_output=True,
                    timeout=10,
                )
                if proc.returncode != 0:
                    errors.append(f"does_not_apply: {proc.stderr.strip()[:200]}")
            except Exception as git_err:
                errors.append(f"git_apply_error: {git_err}")

        return ValidationResult(ok=(len(errors) == 0), errors=errors)
