"""initial_schema

Revision ID: b8a2adbe190a
Revises: 
Create Date: 2026-10-08 15:20:07.672891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a2adbe190a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('content_hash', 'model')
    )
    op.create_table('eval_suites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_eval_suite_name_version')
    )
    op.create_table('repos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suite_id', sa.Uuid(), nullable=False),
    sa.Column('config_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['eval_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mirror_path', sa.Text(), nullable=False),
    sa.Column('repo_map', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'commit_sha', name='uq_repo_snapshot_commit')
    )
    op.create_table('eval_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suite_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('ground_truth', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repo_snapshots.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['eval_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repo_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'path', name='uq_snapshot_file_path')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('budgets', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('config_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repo_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_status_lease', 'tasks', ['status', 'lease_expires_at'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('qualname', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repo_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'path', 'qualname', 'content_hash', name='uq_chunk_identity')
    )
    op.create_index('idx_chunks_path', 'chunks', ['path'], unique=False)
    op.create_index('idx_chunks_qualname', 'chunks', ['qualname'], unique=False)
    op.create_index('idx_chunks_snapshot', 'chunks', ['snapshot_id'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('repeat_idx', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['eval_cases.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'case_id', 'repeat_idx', name='uq_eval_result_case_repeat')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('node', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_name', sa.String(length=64), nullable=True),
    sa.Column('prompt_hash', sa.String(length=16), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_calls_task', 'llm_calls', ['task_id'], unique=False)
    op.create_table('patches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('diff_sha256', sa.String(length=64), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'seq', name='uq_task_event_seq')
    )
    op.create_index('idx_task_events_task_seq', 'task_events', ['task_id', 'seq'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('args_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_tool_calls_task_step', 'tool_calls', ['task_id', 'step_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('patch_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('approver', sa.String(length=128), nullable=False),
    sa.Column('approved_diff_sha256', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approvals')
    op.drop_index('idx_tool_calls_task_step', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index('idx_task_events_task_seq', table_name='task_events')
    op.drop_table('task_events')
    op.drop_table('patches')
    op.drop_index('idx_llm_calls_task', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_table('eval_results')
    op.drop_index('idx_chunks_snapshot', table_name='chunks')
    op.drop_index('idx_chunks_qualname', table_name='chunks')
    op.drop_index('idx_chunks_path', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_tasks_status_lease', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('files')
    op.drop_table('eval_cases')
    op.drop_table('repo_snapshots')
    op.drop_table('eval_runs')
    op.drop_table('repos')
    op.drop_table('eval_suites')
    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
